apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: deploy2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy2k
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy2
    spec:
      containers:
      - image: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        name: nginx
        resources: {}

      
      
status: {}
