apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: first-deply
  name: first-deply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-deply
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: first-deply
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
