apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-app-deploy
  name: sample-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-app-deploy
    spec:
      containers:
      - image: ichiragkumar/backendapp2:6
        name: backendapp2 
        env:
        - name: FIRST_NAME
          valueFrom:
            configMapKeyRef:
              name: sample-cm
              key: first
        - name: LAST_NAME
          valueFrom:
            configMapKeyRef:
              name: sample-cm
              key: last
        ports:
        - containerPort: 3005
        resources: {}
status: {}
