apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-app-deploy
  name: sample-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-app-deploy
    spec:
      containers:
      - image: ichiragkumar/backendapp2
        name: backendapp2
        ports:
        - containerPort: 3000
        resources: {}
status: {}
