apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-app-deploy
  name: sample-app-deploy
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30001

  selector:
    app: sample-app-deploy
  type: NodePort
status:
  loadBalancer: {}
