apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:

    app: sample-app-deploy
  name: sample-app-deploy
spec:
  ports:
  - port: 3005
    protocol: TCP
    targetPort: 3005
    nodePort: 30051
  selector:
    app: sample-app-deploy
  type: NodePort
status:
  loadBalancer: {}
