apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-deployment
  name: my-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30001
  selector:
    app: my-deployment
  type: NodePort
status:
  loadBalancer: {}
